services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: data0804base
      POSTGRES_DB: trabalhomvc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nestjs_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:data0804base@db:5432/trabalhomvc_db"
    depends_on:
      - db

  frontend:
    build: ./web
    container_name: react_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
